### ISSUE TITLE
Request Function (API like)

### ISSUE THREAD

**Issue by sctfic** [lesspass/core#1]
je voudrai coupler LessPass as d'autres outils deja existant afin de remplacer l’interrogation de la base de donné des mdp.

existe t il une API REST (over https) ?

ainsi je pourrai coupler ceci a un fichier excel par exemple
		A			B			C			
1	ClientName	UserLogin0	=lesspass(A1; B1; MasterPass)
2	ClientName	UserLogin1	=lesspass(A2; B2; MasterPass)
3	ClientName	UserLogin2	=lesspass(A3; B3; MasterPass)

**Comment by guillaumevincent** [comment]
This issue was moved to lesspass/lesspass#24
